@baseUrl = http://localhost:5000

#auth-register
GET {{baseUrl}}

###

POST {{baseUrl}}/register
Content-Type: application/json

{
    "fullname": "Trần Minh Quốc",
    "birthday": "2021-12-12",
    "phone_number": "0382374258",
    "email": "minhquoc@gmail.com",
    "password": "Duelingnetword1"
}

###
DELETE {{baseUrl}}/register/2